# Form implementation generated from reading ui file '.\UI\pages_table.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 480)
        Form.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 1)
        self.gridLayout.setRowMinimumHeight(0, 18)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 16)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Prev"))
        self.pushButton_2.setText(_translate("Form", "Next"))
        self.label.setText(_translate("Form", "0/0"))

class CustomTableView(QtWidgets.QWidget):
    def __init__(self, parent: QWidget | None = ..., flags: QtCore.Qt.WindowType = ...) -> None:
        super().__init__(parent, flags)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
