# Form implementation generated from reading ui file '.\UI\pages_table.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 480)
        Form.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_prev = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_prev.sizePolicy().hasHeightForWidth())
        self.btn_prev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        self.btn_prev.setFont(font)
        self.btn_prev.setObjectName("btn_prev")
        self.gridLayout.addWidget(self.btn_prev, 1, 0, 1, 1)
        self.btn_next = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        self.btn_next.setFont(font)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout.addWidget(self.btn_next, 1, 2, 1, 1)
        self.lb_page = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_page.sizePolicy().hasHeightForWidth())
        self.lb_page.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        self.lb_page.setFont(font)
        self.lb_page.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_page.setObjectName("lb_page")
        self.gridLayout.addWidget(self.lb_page, 1, 1, 1, 1)
        self.table = QtWidgets.QTableWidget(parent=Form)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table.setCornerButtonEnabled(False)
        self.table.setRowCount(100)
        self.table.setColumnCount(10)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.table, 0, 0, 1, 3)
        self.gridLayout.setColumnMinimumWidth(0, 1)
        self.gridLayout.setColumnMinimumWidth(1, 1)
        self.gridLayout.setColumnMinimumWidth(2, 1)
        self.gridLayout.setRowMinimumHeight(0, 18)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 16)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_prev.setText(_translate("Form", "Prev"))
        self.btn_next.setText(_translate("Form", "Next"))
        self.lb_page.setText(_translate("Form", "0/0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
