# Form implementation generated from reading ui file '.\UI\add_order.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_order_popup(object):
    def setupUi(self, add_order_popup):
        add_order_popup.setObjectName("add_order_popup")
        add_order_popup.resize(474, 654)
        add_order_popup.setStyleSheet("QDialog{\n"
"    background-color: #ffffff;\n"
"    border: 4px solid rgb(14, 73, 243);\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget{\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLabel{\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTimeEdit, QDateTimeEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(14, 73, 243);\n"
"    color: white;\n"
"    font-family: \'Inter Medium\', sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"      font-style: normal;\n"
"    border: 0px;\n"
"    padding: 8px auto;\n"
"    border-radius: 16px;\n"
"    width: 64px;\n"
"    margin: 0px 32px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"QComboBox::on{\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    alternate-background-color: #fff;\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    border-bottom-left-radius: 16px;\n"
"    border-bottom-right-radius: 16px;\n"
"    padding: 0px 8px 16px 8px;\n"
"}\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    border: 0px;\n"
"    image: ;\n"
"}\n"
"\n"
" QDateEdit QCalendarWidget QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 0px;\n"
"     selection-background-color: rgb(188, 206, 253);\n"
" }\n"
"\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    border: 0px;\n"
"}\n"
"QTimeEdit::up-button{\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"QTimeEdit::down-button{\n"
"    border-bottom-right-radius: 16px;\n"
"}\n"
"QDateTimeEdit{\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QDateTimeEdit::drop-down {\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"\n"
"QDateTimeEdit QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    border: 0px;\n"
"}\n"
"\n"
" QDateTimeEdit QCalendarWidget QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 0px;\n"
"     selection-background-color: rgb(188, 206, 253);\n"
" }")
        self.verticalLayout = QtWidgets.QVBoxLayout(add_order_popup)
        self.verticalLayout.setContentsMargins(32, 16, 32, 16)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(parent=add_order_popup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        self.header.setFont(font)
        self.header.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.header.setScaledContents(True)
        self.header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.input_form = QtWidgets.QWidget(parent=add_order_popup)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_form.setFont(font)
        self.input_form.setStyleSheet("")
        self.input_form.setObjectName("input_form")
        self.gridLayout = QtWidgets.QGridLayout(self.input_form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.txt_cus_id = QtWidgets.QLineEdit(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_cus_id.sizePolicy().hasHeightForWidth())
        self.txt_cus_id.setSizePolicy(sizePolicy)
        self.txt_cus_id.setObjectName("txt_cus_id")
        self.verticalLayout_6.addWidget(self.txt_cus_id)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.txt_saler = QtWidgets.QLineEdit(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_saler.sizePolicy().hasHeightForWidth())
        self.txt_saler.setSizePolicy(sizePolicy)
        self.txt_saler.setObjectName("txt_saler")
        self.verticalLayout_3.addWidget(self.txt_saler)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget_3)
        self.tableWidget.setStyleSheet("QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}     \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"} \n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    height: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 0px 0px 0px 0px;\n"
"}     \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"} \n"
"\n"
"QHeaderView::section {\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}")
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(64)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(32)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.txt_total = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        self.txt_total.setFont(font)
        self.txt_total.setObjectName("txt_total")
        self.verticalLayout_4.addWidget(self.txt_total)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 2)
        self.widget = QtWidgets.QWidget(parent=self.input_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.txt_discount = QtWidgets.QLineEdit(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_discount.sizePolicy().hasHeightForWidth())
        self.txt_discount.setSizePolicy(sizePolicy)
        self.txt_discount.setObjectName("txt_discount")
        self.verticalLayout_2.addWidget(self.txt_discount)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(parent=self.input_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.txt_paid = QtWidgets.QLineEdit(parent=self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_paid.sizePolicy().hasHeightForWidth())
        self.txt_paid.setSizePolicy(sizePolicy)
        self.txt_paid.setObjectName("txt_paid")
        self.verticalLayout_5.addWidget(self.txt_paid)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_4, 3, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.created_time = QtWidgets.QDateTimeEdit(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.created_time.sizePolicy().hasHeightForWidth())
        self.created_time.setSizePolicy(sizePolicy)
        self.created_time.setCalendarPopup(True)
        self.created_time.setObjectName("created_time")
        self.verticalLayout_7.addWidget(self.created_time)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 3)
        self.gridLayout.setRowStretch(3, 1)
        self.verticalLayout.addWidget(self.input_form)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=add_order_popup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 3)

        self.retranslateUi(add_order_popup)
        self.buttonBox.accepted.connect(add_order_popup.accept) # type: ignore
        self.buttonBox.rejected.connect(add_order_popup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_order_popup)

    def retranslateUi(self, add_order_popup):
        _translate = QtCore.QCoreApplication.translate
        add_order_popup.setWindowTitle(_translate("add_order_popup", "New Order"))
        self.header.setText(_translate("add_order_popup", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">New Order</span></p></body></html>"))
        self.label_5.setText(_translate("add_order_popup", "Customer ID:"))
        self.label_2.setText(_translate("add_order_popup", "Saler ID:"))
        self.label_3.setText(_translate("add_order_popup", "Products:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("add_order_popup", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("add_order_popup", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("add_order_popup", "Price Unit"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("add_order_popup", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("add_order_popup", "Total"))
        self.txt_total.setText(_translate("add_order_popup", "Total:"))
        self.label.setText(_translate("add_order_popup", "Discount:"))
        self.label_7.setText(_translate("add_order_popup", "Customer paid:"))
        self.label_6.setText(_translate("add_order_popup", "Created Time:"))
        self.created_time.setDisplayFormat(_translate("add_order_popup", "MM/dd/yyyy hh:mm:ss AP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_order_popup = QtWidgets.QDialog()
    ui = Ui_add_order_popup()
    ui.setupUi(add_order_popup)
    add_order_popup.show()
    sys.exit(app.exec())
