# Form implementation generated from reading ui file './UI/ultimate-design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_screen(object):
    def setupUi(self, main_screen):
        main_screen.setObjectName("main_screen")
        main_screen.resize(1230, 720)
        font = QtGui.QFont()
        font.setFamily("Inter ExtraBold")
        font.setBold(True)
        main_screen.setFont(font)
        main_screen.setStyleSheet("QWidget {\n"
"    background-color: #ffffff\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(main_screen)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.side_bar = QtWidgets.QWidget(parent=main_screen)
        self.side_bar.setStyleSheet("QWidget{\n"
"    border-right: 1px solid rgb(122, 123, 129);\n"
"}")
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Inter ExtraBold")
        font.setPointSize(24)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tab_button = QtWidgets.QWidget(parent=self.side_bar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tab_button.setFont(font)
        self.tab_button.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.tab_button.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(188, 206, 253);\n"
"    padding-right: 8px;\n"
"    color: rgb(112, 112, 112);\n"
"    border-top-left-radius: 16px;\n"
"    border-bottom-left-radius: 16px;\n"
"}\n"
"\n"
"QRadioButton:checked{\n"
"    background-color: rgb(14, 73, 243);\n"
"    color: rgb(240, 247, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator{\n"
"    width: 0px;\n"
"}")
        self.tab_button.setObjectName("tab_button")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_button)
        self.verticalLayout_2.setContentsMargins(32, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_dashboard = QtWidgets.QRadioButton(parent=self.tab_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dashboard.sizePolicy().hasHeightForWidth())
        self.btn_dashboard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.btn_dashboard.setFont(font)
        self.btn_dashboard.setChecked(True)
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.verticalLayout_2.addWidget(self.btn_dashboard)
        self.btn_order = QtWidgets.QRadioButton(parent=self.tab_button)
        self.btn_order.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_order.sizePolicy().hasHeightForWidth())
        self.btn_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.btn_order.setFont(font)
        self.btn_order.setChecked(False)
        self.btn_order.setObjectName("btn_order")
        self.verticalLayout_2.addWidget(self.btn_order)
        self.btn_product = QtWidgets.QRadioButton(parent=self.tab_button)
        self.btn_product.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_product.sizePolicy().hasHeightForWidth())
        self.btn_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.btn_product.setFont(font)
        self.btn_product.setObjectName("btn_product")
        self.verticalLayout_2.addWidget(self.btn_product)
        self.btn_customer = QtWidgets.QRadioButton(parent=self.tab_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_customer.sizePolicy().hasHeightForWidth())
        self.btn_customer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.btn_customer.setFont(font)
        self.btn_customer.setObjectName("btn_customer")
        self.verticalLayout_2.addWidget(self.btn_customer)
        self.btn_staff = QtWidgets.QRadioButton(parent=self.tab_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_staff.sizePolicy().hasHeightForWidth())
        self.btn_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.btn_staff.setFont(font)
        self.btn_staff.setObjectName("btn_staff")
        self.verticalLayout_2.addWidget(self.btn_staff)
        self.verticalLayout.addWidget(self.tab_button)
        self.tool_button = QtWidgets.QWidget(parent=self.side_bar)
        self.tool_button.setObjectName("tool_button")
        self.verticalLayout.addWidget(self.tool_button)
        self.verticalLayout.setStretch(0, 16)
        self.verticalLayout.setStretch(1, 39)
        self.verticalLayout.setStretch(2, 32)
        self.gridLayout.addWidget(self.side_bar, 0, 0, 1, 1)
        self.content = QtWidgets.QWidget(parent=main_screen)
        self.content.setObjectName("content")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stack_content_pages = QtWidgets.QStackedWidget(parent=self.content)
        self.stack_content_pages.setStyleSheet("QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"")
        self.stack_content_pages.setObjectName("stack_content_pages")
        self.dash_board = QtWidgets.QWidget()
        self.dash_board.setStyleSheet("#dash_board{\n"
"    background-color: #ffffff;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"#list_item_6{\n"
"    background: rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}\n"
"")
        self.dash_board.setObjectName("dash_board")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dash_board)
        self.verticalLayout_3.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.head_bar_6 = QtWidgets.QWidget(parent=self.dash_board)
        self.head_bar_6.setStyleSheet("QPushButton{\n"
"    margin: 0px 0px 96px 0px;\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.head_bar_6.setObjectName("head_bar_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.head_bar_6)
        self.gridLayout_7.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_7.setSpacing(16)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_exe_query = QtWidgets.QPushButton(parent=self.head_bar_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exe_query.sizePolicy().hasHeightForWidth())
        self.btn_exe_query.setSizePolicy(sizePolicy)
        self.btn_exe_query.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_exe_query.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_exe_query.setFont(font)
        self.btn_exe_query.setObjectName("btn_exe_query")
        self.gridLayout_7.addWidget(self.btn_exe_query, 0, 0, 1, 1)
        self.txt_query = QtWidgets.QTextEdit(parent=self.head_bar_6)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        font.setItalic(False)
        self.txt_query.setFont(font)
        self.txt_query.setStyleSheet("background-color: #ffffff;\n"
"padding-right: 16px;\n"
" font-family:\'Courier\'; \n"
"font-size:12pt;  \n"
"font-style:normal;")
        self.txt_query.setObjectName("txt_query")
        self.gridLayout_7.addWidget(self.txt_query, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 13)
        self.verticalLayout_3.addWidget(self.head_bar_6)
        self.list_item_6 = QtWidgets.QWidget(parent=self.dash_board)
        self.list_item_6.setObjectName("list_item_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.list_item_6)
        self.verticalLayout_11.setContentsMargins(4, 0, 20, 20)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.table_result = QtWidgets.QTableWidget(parent=self.list_item_6)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(False)
        self.table_result.setFont(font)
        self.table_result.setMouseTracking(False)
        self.table_result.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.table_result.setAutoFillBackground(False)
        self.table_result.setLineWidth(0)
        self.table_result.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.table_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.table_result.setAlternatingRowColors(True)
        self.table_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_result.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.table_result.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.table_result.setShowGrid(False)
        self.table_result.setCornerButtonEnabled(False)
        self.table_result.setRowCount(20)
        self.table_result.setColumnCount(10)
        self.table_result.setObjectName("table_result")
        item = QtWidgets.QTableWidgetItem()
        self.table_result.setItem(0, 0, item)
        self.table_result.horizontalHeader().setCascadingSectionResizes(True)
        self.table_result.horizontalHeader().setSortIndicatorShown(False)
        self.table_result.horizontalHeader().setStretchLastSection(True)
        self.table_result.verticalHeader().setCascadingSectionResizes(True)
        self.table_result.verticalHeader().setDefaultSectionSize(32)
        self.table_result.verticalHeader().setMinimumSectionSize(32)
        self.table_result.verticalHeader().setSortIndicatorShown(False)
        self.table_result.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_11.addWidget(self.table_result)
        self.verticalLayout_3.addWidget(self.list_item_6)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.stack_content_pages.addWidget(self.dash_board)
        self.order_view = QtWidgets.QWidget()
        self.order_view.setStyleSheet("QWidget#order_view{\n"
"    background-color: #ffffff;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"#list_item_4{\n"
"    background: rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.order_view.setObjectName("order_view")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.order_view)
        self.gridLayout_6.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_6.setSpacing(16)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.head_bar_4 = QtWidgets.QWidget(parent=self.order_view)
        self.head_bar_4.setStyleSheet("QPushButton{\n"
"    margin: 0px 48px 0px 0px;\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.head_bar_4.setObjectName("head_bar_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.head_bar_4)
        self.horizontalLayout_8.setContentsMargins(8, 8, 16, 8)
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(parent=self.head_bar_4)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.txt_search_order = QtWidgets.QLineEdit(parent=self.head_bar_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_search_order.sizePolicy().hasHeightForWidth())
        self.txt_search_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.txt_search_order.setFont(font)
        self.txt_search_order.setStyleSheet("background-color: #fff;")
        self.txt_search_order.setText("")
        self.txt_search_order.setObjectName("txt_search_order")
        self.horizontalLayout_8.addWidget(self.txt_search_order)
        self.btn_add_order = QtWidgets.QPushButton(parent=self.head_bar_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_order.sizePolicy().hasHeightForWidth())
        self.btn_add_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_add_order.setFont(font)
        self.btn_add_order.setObjectName("btn_add_order")
        self.horizontalLayout_8.addWidget(self.btn_add_order)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 7)
        self.horizontalLayout_8.setStretch(2, 2)
        self.gridLayout_6.addWidget(self.head_bar_4, 0, 0, 1, 2)
        self.list_item_4 = QtWidgets.QWidget(parent=self.order_view)
        self.list_item_4.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.list_item_4.setObjectName("list_item_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.list_item_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 32, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.table_order = CustomTableView(parent=self.list_item_4)
        self.table_order.setObjectName("table_order")
        self.horizontalLayout_9.addWidget(self.table_order)
        self.gridLayout_6.addWidget(self.list_item_4, 1, 0, 1, 1)
        self.order_detail_view = QtWidgets.QWidget(parent=self.order_view)
        self.order_detail_view.setStyleSheet("QTextEdit{\n"
"    border: 1px solid rgb(112, 112, 112);\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(217, 217, 217);\n"
"    margin: 0px 0px 0px 0px;\n"
"}      ")
        self.order_detail_view.setObjectName("order_detail_view")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.order_detail_view)
        self.verticalLayout_9.setContentsMargins(16, 32, 16, 32)
        self.verticalLayout_9.setSpacing(16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.info_order = QtWidgets.QTextEdit(parent=self.order_detail_view)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.info_order.setFont(font)
        self.info_order.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.info_order.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.info_order.setLineWidth(0)
        self.info_order.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.info_order.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.FixedColumnWidth)
        self.info_order.setReadOnly(True)
        self.info_order.setObjectName("info_order")
        self.verticalLayout_9.addWidget(self.info_order)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_7.setSpacing(32)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_del_order = QtWidgets.QPushButton(parent=self.order_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_order.sizePolicy().hasHeightForWidth())
        self.btn_del_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_del_order.setFont(font)
        self.btn_del_order.setStyleSheet("background-color: #FF4500;")
        self.btn_del_order.setObjectName("btn_del_order")
        self.horizontalLayout_7.addWidget(self.btn_del_order)
        self.btn_update_order = QtWidgets.QPushButton(parent=self.order_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_order.sizePolicy().hasHeightForWidth())
        self.btn_update_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_update_order.setFont(font)
        self.btn_update_order.setObjectName("btn_update_order")
        self.horizontalLayout_7.addWidget(self.btn_update_order)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.setStretch(0, 11)
        self.verticalLayout_9.setStretch(1, 1)
        self.gridLayout_6.addWidget(self.order_detail_view, 1, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 13)
        self.gridLayout_6.setColumnStretch(1, 7)
        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 11)
        self.stack_content_pages.addWidget(self.order_view)
        self.product_view = QtWidgets.QWidget()
        self.product_view.setStyleSheet("QWidget#product_view{\n"
"    background-color: #ffffff;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"#list_item_3{\n"
"    background: rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.product_view.setObjectName("product_view")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.product_view)
        self.gridLayout_5.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_5.setSpacing(16)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.head_bar_3 = QtWidgets.QWidget(parent=self.product_view)
        self.head_bar_3.setStyleSheet("QPushButton{\n"
"    margin: 0px 48px 0px 0px;\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.head_bar_3.setObjectName("head_bar_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.head_bar_3)
        self.horizontalLayout_5.setContentsMargins(8, 8, 16, 8)
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.head_bar_3)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txt_search_product = QtWidgets.QLineEdit(parent=self.head_bar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_search_product.sizePolicy().hasHeightForWidth())
        self.txt_search_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.txt_search_product.setFont(font)
        self.txt_search_product.setStyleSheet("background-color: #fff;")
        self.txt_search_product.setText("")
        self.txt_search_product.setObjectName("txt_search_product")
        self.horizontalLayout_5.addWidget(self.txt_search_product)
        self.btn_add_product = QtWidgets.QPushButton(parent=self.head_bar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_product.sizePolicy().hasHeightForWidth())
        self.btn_add_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_add_product.setFont(font)
        self.btn_add_product.setObjectName("btn_add_product")
        self.horizontalLayout_5.addWidget(self.btn_add_product)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 7)
        self.horizontalLayout_5.setStretch(2, 2)
        self.gridLayout_5.addWidget(self.head_bar_3, 0, 0, 1, 2)
        self.list_item_3 = QtWidgets.QWidget(parent=self.product_view)
        self.list_item_3.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.list_item_3.setObjectName("list_item_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.list_item_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 32, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_product = CustomTableView(parent=self.list_item_3)
        self.table_product.setObjectName("table_product")
        self.verticalLayout_4.addWidget(self.table_product)
        self.gridLayout_5.addWidget(self.list_item_3, 1, 0, 1, 1)
        self.product_detail_view = QtWidgets.QWidget(parent=self.product_view)
        self.product_detail_view.setStyleSheet("QTextEdit{\n"
"    border: 1px solid rgb(112, 112, 112);\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(217, 217, 217);\n"
"    margin: 0px 0px 0px 0px;\n"
"}      ")
        self.product_detail_view.setObjectName("product_detail_view")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.product_detail_view)
        self.verticalLayout_8.setContentsMargins(16, 32, 16, 32)
        self.verticalLayout_8.setSpacing(16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.info_product = QtWidgets.QTextEdit(parent=self.product_detail_view)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.info_product.setFont(font)
        self.info_product.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.info_product.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.info_product.setLineWidth(0)
        self.info_product.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.info_product.setReadOnly(True)
        self.info_product.setObjectName("info_product")
        self.verticalLayout_8.addWidget(self.info_product)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_6.setSpacing(32)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_del_product = QtWidgets.QPushButton(parent=self.product_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_product.sizePolicy().hasHeightForWidth())
        self.btn_del_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_del_product.setFont(font)
        self.btn_del_product.setStyleSheet("background-color: #FF4500;")
        self.btn_del_product.setObjectName("btn_del_product")
        self.horizontalLayout_6.addWidget(self.btn_del_product)
        self.btn_update_product = QtWidgets.QPushButton(parent=self.product_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_product.sizePolicy().hasHeightForWidth())
        self.btn_update_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_update_product.setFont(font)
        self.btn_update_product.setObjectName("btn_update_product")
        self.horizontalLayout_6.addWidget(self.btn_update_product)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.setStretch(0, 11)
        self.verticalLayout_8.setStretch(1, 1)
        self.gridLayout_5.addWidget(self.product_detail_view, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 13)
        self.gridLayout_5.setColumnStretch(1, 7)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 11)
        self.stack_content_pages.addWidget(self.product_view)
        self.customer_view = QtWidgets.QWidget()
        self.customer_view.setStyleSheet("#customer_view{\n"
"    background-color: #ffffff;\n"
"    border-radius: 0px;\n"
"}\n"
"QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"#list_item_2{\n"
"    background: rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}\n"
"")
        self.customer_view.setObjectName("customer_view")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.customer_view)
        self.gridLayout_4.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_4.setSpacing(16)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.head_bar_2 = QtWidgets.QWidget(parent=self.customer_view)
        self.head_bar_2.setStyleSheet("QPushButton{\n"
"    margin: 0px 48px 0px 0px;\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.head_bar_2.setObjectName("head_bar_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.head_bar_2)
        self.horizontalLayout_4.setContentsMargins(8, 8, 16, 8)
        self.horizontalLayout_4.setSpacing(16)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.head_bar_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txt_search_customer = QtWidgets.QLineEdit(parent=self.head_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_search_customer.sizePolicy().hasHeightForWidth())
        self.txt_search_customer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.txt_search_customer.setFont(font)
        self.txt_search_customer.setStyleSheet("background-color: #fff;")
        self.txt_search_customer.setText("")
        self.txt_search_customer.setObjectName("txt_search_customer")
        self.horizontalLayout_4.addWidget(self.txt_search_customer)
        self.btn_add_customer = QtWidgets.QPushButton(parent=self.head_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_customer.sizePolicy().hasHeightForWidth())
        self.btn_add_customer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_add_customer.setFont(font)
        self.btn_add_customer.setObjectName("btn_add_customer")
        self.horizontalLayout_4.addWidget(self.btn_add_customer)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 7)
        self.horizontalLayout_4.setStretch(2, 2)
        self.gridLayout_4.addWidget(self.head_bar_2, 0, 0, 1, 2)
        self.list_view = QtWidgets.QWidget(parent=self.customer_view)
        self.list_view.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.list_view.setObjectName("list_view")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.list_view)
        self.horizontalLayout_2.setContentsMargins(0, 0, 32, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_customer = CustomTableView(parent=self.list_view)
        self.table_customer.setObjectName("table_customer")
        self.horizontalLayout_2.addWidget(self.table_customer)
        self.gridLayout_4.addWidget(self.list_view, 1, 0, 1, 1)
        self.customer_detail_view = QtWidgets.QWidget(parent=self.customer_view)
        self.customer_detail_view.setStyleSheet("QTextEdit{\n"
"    border: 1px solid rgb(112, 112, 112);\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(217, 217, 217);\n"
"    margin: 0px 0px 0px 0px;\n"
"}      ")
        self.customer_detail_view.setObjectName("customer_detail_view")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.customer_detail_view)
        self.verticalLayout_5.setContentsMargins(16, 32, 16, 32)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.info_customer = QtWidgets.QTextEdit(parent=self.customer_detail_view)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.info_customer.setFont(font)
        self.info_customer.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.info_customer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.info_customer.setLineWidth(0)
        self.info_customer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.info_customer.setReadOnly(True)
        self.info_customer.setObjectName("info_customer")
        self.verticalLayout_5.addWidget(self.info_customer)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_3.setSpacing(32)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_del_customer = QtWidgets.QPushButton(parent=self.customer_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_customer.sizePolicy().hasHeightForWidth())
        self.btn_del_customer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_del_customer.setFont(font)
        self.btn_del_customer.setStyleSheet("background-color: #FF4500;")
        self.btn_del_customer.setObjectName("btn_del_customer")
        self.horizontalLayout_3.addWidget(self.btn_del_customer)
        self.btn_update_customer = QtWidgets.QPushButton(parent=self.customer_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_customer.sizePolicy().hasHeightForWidth())
        self.btn_update_customer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_update_customer.setFont(font)
        self.btn_update_customer.setObjectName("btn_update_customer")
        self.horizontalLayout_3.addWidget(self.btn_update_customer)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(0, 11)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout_4.addWidget(self.customer_detail_view, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 13)
        self.gridLayout_4.setColumnStretch(1, 7)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 11)
        self.stack_content_pages.addWidget(self.customer_view)
        self.staff_view = QtWidgets.QWidget()
        self.staff_view.setStyleSheet("QWidget#staff_view{\n"
"    background-color: #ffffff;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"}\n"
"#list_item_5{\n"
"    background: rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.staff_view.setObjectName("staff_view")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.staff_view)
        self.gridLayout_3.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_3.setSpacing(16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.head_bar_5 = QtWidgets.QWidget(parent=self.staff_view)
        self.head_bar_5.setStyleSheet("QPushButton{\n"
"    margin: 0px 48px 0px 0px;\n"
"    color: white;\n"
"    background-color:rgb(14, 73, 243);\n"
"}")
        self.head_bar_5.setObjectName("head_bar_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.head_bar_5)
        self.horizontalLayout_12.setContentsMargins(8, 8, 16, 8)
        self.horizontalLayout_12.setSpacing(16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(parent=self.head_bar_5)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.txt_search_staff = QtWidgets.QLineEdit(parent=self.head_bar_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_search_staff.sizePolicy().hasHeightForWidth())
        self.txt_search_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.txt_search_staff.setFont(font)
        self.txt_search_staff.setStyleSheet("background-color: #fff;")
        self.txt_search_staff.setText("")
        self.txt_search_staff.setObjectName("txt_search_staff")
        self.horizontalLayout_12.addWidget(self.txt_search_staff)
        self.btn_add_staff = QtWidgets.QPushButton(parent=self.head_bar_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_staff.sizePolicy().hasHeightForWidth())
        self.btn_add_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_add_staff.setFont(font)
        self.btn_add_staff.setObjectName("btn_add_staff")
        self.horizontalLayout_12.addWidget(self.btn_add_staff)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 7)
        self.horizontalLayout_12.setStretch(2, 2)
        self.gridLayout_3.addWidget(self.head_bar_5, 0, 0, 1, 2)
        self.list_item_5 = QtWidgets.QWidget(parent=self.staff_view)
        self.list_item_5.setStyleSheet("QWidget{\n"
"    background:rgb(188, 206, 253);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 0px;\n"
"    background:rgb(217, 217, 217);\n"
"    height: 4px;\n"
"    margin: 0px 0px 0 40px;\n"
"}       \n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(112, 112, 112);\n"
"    min-width: 32px;\n"
"}        \n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    width: 64px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 0px;\n"
"    width: 4px;\n"
"    background:rgb(217, 217, 217);\n"
"    margin: 26px 0px 0px 0px;\n"
"}       \n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(112, 112, 112);\n"
"    min-height: 32px;\n"
"}        \n"
"QScrollBar::add-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 0px;\n"
"    background: rgb(188, 206, 253);\n"
"    height: 64px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QHeaderView{\n"
"    background-color: rgb(188, 206, 253);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    color: rgb(112, 112, 112);\n"
"    border: 0px;\n"
"    padding: 2px 4px 2px 4px;        \n"
"    font-size: 12px;\n"
"    font-family: Inter; \n"
"    font-weight: bold;\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(188, 206, 253);\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QTableWidget { \n"
"    background-color: #ffffff;\n"
"    border-width: 0px;\n"
"    border-top-left-radius: 16px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTextEdit{\n"
"    background-color: #ffffff;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QPushButton, QLabel {\n"
"    color: rgb(112, 112, 112);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #fff;\n"
"}\n"
"")
        self.list_item_5.setObjectName("list_item_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.list_item_5)
        self.horizontalLayout.setContentsMargins(0, 0, 32, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_staff = CustomTableView(parent=self.list_item_5)
        self.table_staff.setObjectName("table_staff")
        self.horizontalLayout.addWidget(self.table_staff)
        self.gridLayout_3.addWidget(self.list_item_5, 1, 0, 1, 1)
        self.staff_detail_view = QtWidgets.QWidget(parent=self.staff_view)
        self.staff_detail_view.setStyleSheet("QTextEdit{\n"
"    border: 1px solid rgb(112, 112, 112);\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(217, 217, 217);\n"
"    margin: 0px 0px 0px 0px;\n"
"}      ")
        self.staff_detail_view.setObjectName("staff_detail_view")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.staff_detail_view)
        self.verticalLayout_13.setContentsMargins(16, 32, 16, 32)
        self.verticalLayout_13.setSpacing(16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.info_staff = QtWidgets.QTextEdit(parent=self.staff_detail_view)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.info_staff.setFont(font)
        self.info_staff.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.info_staff.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.info_staff.setLineWidth(0)
        self.info_staff.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.info_staff.setReadOnly(True)
        self.info_staff.setObjectName("info_staff")
        self.verticalLayout_13.addWidget(self.info_staff)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(16, 4, 32, 4)
        self.horizontalLayout_11.setSpacing(32)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_del_staff = QtWidgets.QPushButton(parent=self.staff_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del_staff.sizePolicy().hasHeightForWidth())
        self.btn_del_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_del_staff.setFont(font)
        self.btn_del_staff.setStyleSheet("background-color: #FF4500;")
        self.btn_del_staff.setObjectName("btn_del_staff")
        self.horizontalLayout_11.addWidget(self.btn_del_staff)
        self.btn_update_staff = QtWidgets.QPushButton(parent=self.staff_detail_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_staff.sizePolicy().hasHeightForWidth())
        self.btn_update_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        self.btn_update_staff.setFont(font)
        self.btn_update_staff.setObjectName("btn_update_staff")
        self.horizontalLayout_11.addWidget(self.btn_update_staff)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_13.setStretch(0, 11)
        self.verticalLayout_13.setStretch(1, 1)
        self.gridLayout_3.addWidget(self.staff_detail_view, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 13)
        self.gridLayout_3.setColumnStretch(1, 7)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 11)
        self.stack_content_pages.addWidget(self.staff_view)
        self.gridLayout_2.addWidget(self.stack_content_pages, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.content, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 5)

        self.retranslateUi(main_screen)
        self.stack_content_pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(main_screen)

    def retranslateUi(self, main_screen):
        _translate = QtCore.QCoreApplication.translate
        main_screen.setWindowTitle(_translate("main_screen", "Group 12 - Mini Super Market"))
        self.label.setText(_translate("main_screen", "<html><head/><body><p align=\"center\"><span style=\" color:#0e49f3;\">Group 12</span></p></body></html>"))
        self.btn_dashboard.setText(_translate("main_screen", "General"))
        self.btn_order.setText(_translate("main_screen", "Orders"))
        self.btn_product.setText(_translate("main_screen", "Products"))
        self.btn_customer.setText(_translate("main_screen", "Customers"))
        self.btn_staff.setText(_translate("main_screen", "Staffs"))
        self.btn_exe_query.setText(_translate("main_screen", "Execute"))
        self.txt_query.setHtml(_translate("main_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Courier\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.table_result.setSortingEnabled(False)
        __sortingEnabled = self.table_result.isSortingEnabled()
        self.table_result.setSortingEnabled(False)
        self.table_result.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("main_screen", "Search:"))
        self.btn_add_order.setText(_translate("main_screen", "New Order"))
        self.info_order.setHtml(_translate("main_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Inter\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_del_order.setText(_translate("main_screen", "Delete"))
        self.btn_update_order.setText(_translate("main_screen", "Update"))
        self.label_4.setText(_translate("main_screen", "Search:"))
        self.btn_add_product.setText(_translate("main_screen", "New Product"))
        self.info_product.setHtml(_translate("main_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Inter\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_del_product.setText(_translate("main_screen", "Delete"))
        self.btn_update_product.setText(_translate("main_screen", "Update"))
        self.label_3.setText(_translate("main_screen", "Search:"))
        self.btn_add_customer.setText(_translate("main_screen", "New Customer"))
        self.info_customer.setHtml(_translate("main_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Inter\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_del_customer.setText(_translate("main_screen", "Delete"))
        self.btn_update_customer.setText(_translate("main_screen", "Update"))
        self.label_7.setText(_translate("main_screen", "Search:"))
        self.btn_add_staff.setText(_translate("main_screen", "New Staff"))
        self.info_staff.setHtml(_translate("main_screen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Inter\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_del_staff.setText(_translate("main_screen", "Delete"))
        self.btn_update_staff.setText(_translate("main_screen", "Update"))
from .CustomWidgets.CustomTableView import CustomTableView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_screen = QtWidgets.QWidget()
    ui = Ui_main_screen()
    ui.setupUi(main_screen)
    main_screen.show()
    sys.exit(app.exec())
