# Form implementation generated from reading ui file '.\UI\add_product.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SupplyProduct(object):
    def setupUi(self, SupplyProduct):
        SupplyProduct.setObjectName("SupplyProduct")
        SupplyProduct.resize(542, 644)
        SupplyProduct.setStyleSheet("QDialog{\n"
"    background-color: #ffffff;\n"
"    border: 4px solid rgb(14, 73, 243);\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget{\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QLabel{\n"
"    padding-left: 8px;\n"
"}\n"
"\n"
"QLineEdit, QDateEdit, QComboBox, QTimeEdit, QDateTimeEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius: 16px;\n"
"    padding-left: 16px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(14, 73, 243);\n"
"    color: white;\n"
"    font-family: \'Inter Medium\', sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"      font-style: normal;\n"
"    border: 0px;\n"
"    padding: 8px auto;\n"
"    border-radius: 16px;\n"
"    width: 64px;\n"
"    margin: 0px 32px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"QComboBox::on{\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    alternate-background-color: #fff;\n"
"    border: 2px solid rgb(14, 73, 243);\n"
"    border-bottom-left-radius: 16px;\n"
"    border-bottom-right-radius: 16px;\n"
"    padding: 0px 8px 16px 8px;\n"
"}\n"
"\n"
"\n"
"QDateEdit::drop-down {\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"\n"
"QDateEdit QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    border: 0px;\n"
"    image: ;\n"
"}\n"
"\n"
" QDateEdit QCalendarWidget QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 0px;\n"
"     selection-background-color: rgb(188, 206, 253);\n"
" }\n"
"\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    border: 0px;\n"
"}\n"
"QTimeEdit::up-button{\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"QTimeEdit::down-button{\n"
"    border-bottom-right-radius: 16px;\n"
"}\n"
"QDateTimeEdit{\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QDateTimeEdit::drop-down {\n"
"    width: 16px;\n"
"    margin-right: 16px;\n"
"    border-top-right-radius: 16px;\n"
"}\n"
"\n"
"QDateTimeEdit QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    border: 0px;\n"
"}\n"
"\n"
" QDateTimeEdit QCalendarWidget QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 0px;\n"
"     selection-background-color: rgb(188, 206, 253);\n"
" }")
        self.verticalLayout = QtWidgets.QVBoxLayout(SupplyProduct)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(parent=SupplyProduct)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        self.header.setFont(font)
        self.header.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.header.setScaledContents(True)
        self.header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.input_form = QtWidgets.QWidget(parent=SupplyProduct)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_form.setFont(font)
        self.input_form.setStyleSheet("")
        self.input_form.setObjectName("input_form")
        self.gridLayout = QtWidgets.QGridLayout(self.input_form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.txt_title = QtWidgets.QLineEdit(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_title.sizePolicy().hasHeightForWidth())
        self.txt_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_title.setFont(font)
        self.txt_title.setObjectName("txt_title")
        self.verticalLayout_3.addWidget(self.txt_title)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 3)
        self.widget_5 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.txt_quantity = QtWidgets.QLineEdit(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_quantity.sizePolicy().hasHeightForWidth())
        self.txt_quantity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_quantity.setFont(font)
        self.txt_quantity.setObjectName("txt_quantity")
        self.verticalLayout_5.addWidget(self.txt_quantity)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.txt_suplier = QtWidgets.QLineEdit(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_suplier.sizePolicy().hasHeightForWidth())
        self.txt_suplier.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_suplier.setFont(font)
        self.txt_suplier.setObjectName("txt_suplier")
        self.verticalLayout_7.addWidget(self.txt_suplier)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_7, 1, 0, 1, 2)
        self.widget_10 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.txt_price = QtWidgets.QLineEdit(parent=self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_price.sizePolicy().hasHeightForWidth())
        self.txt_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_price.setFont(font)
        self.txt_price.setObjectName("txt_price")
        self.verticalLayout_10.addWidget(self.txt_price)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_10, 1, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(parent=self.input_form)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.created_time = QtWidgets.QDateTimeEdit(parent=self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.created_time.sizePolicy().hasHeightForWidth())
        self.created_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.created_time.setFont(font)
        self.created_time.setCurrentSection(QtWidgets.QDateTimeEdit.Section.MonthSection)
        self.created_time.setCalendarPopup(True)
        self.created_time.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.created_time.setObjectName("created_time")
        self.verticalLayout_6.addWidget(self.created_time)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.gridLayout.addWidget(self.widget_6, 2, 1, 1, 2)
        self.gridLayout.setRowMinimumHeight(0, 1)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setRowMinimumHeight(2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addWidget(self.input_form)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SupplyProduct)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 3)

        self.retranslateUi(SupplyProduct)
        self.buttonBox.accepted.connect(SupplyProduct.accept) # type: ignore
        self.buttonBox.rejected.connect(SupplyProduct.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SupplyProduct)

    def retranslateUi(self, SupplyProduct):
        _translate = QtCore.QCoreApplication.translate
        SupplyProduct.setWindowTitle(_translate("SupplyProduct", "Supply Product"))
        self.header.setText(_translate("SupplyProduct", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Supply Product</span></p></body></html>"))
        self.label_3.setText(_translate("SupplyProduct", "Title"))
        self.label_5.setText(_translate("SupplyProduct", "Quantity"))
        self.label_7.setText(_translate("SupplyProduct", "Suplier"))
        self.label_10.setText(_translate("SupplyProduct", "Price"))
        self.label_6.setText(_translate("SupplyProduct", "Created Time"))
        self.created_time.setDisplayFormat(_translate("SupplyProduct", "MM/dd/yyyy hh:mm:ss A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SupplyProduct = QtWidgets.QDialog()
    ui = Ui_SupplyProduct()
    ui.setupUi(SupplyProduct)
    SupplyProduct.show()
    sys.exit(app.exec())
